(*
This is a script to transfer a single transaction from an encouter to another encounter on Revenue Cycle Application
Ma046396
01/30/2017
*)

(*Prerequisities:
1. Ensure Starting Point is at Patient Account Perspective 
2. Ensure Transfer Transaction Window is in Java version unless otherwise is required for testing
3. Ensure a transaction is available for transfer
4. Note position of transaction to be transfer
*)


Put "1.00" into amount
Put "Money Order" into PaymentMethod
Put "01/02/2018" into PayDate


Click (Image:"DropDownMenu", WaitFor:2)
Click Text:"Apply Self Pay Remittance", searchRectangle:((783,214,952,306))
if imagefound("ViewCertificate")
	Repeat 2 times
		Click (Image:"ViewCertificate", WaitFor:2)
	End Repeat
end if
wait 1
Click (Image:"Remittance", WaitFor:3)
SwipeLeft "Remittance"
TypeText amount
Click "PaymentAlias"
Typetext downArrow, returnkey
Click "AddButton"

Click "AmountTendered"//, searchRectangle:((115,395,453,550))
TypeText amount
Click (Image:"MethodofPayment", WaitFor:1)
Click Text:PaymentMethod, searchRectangle:((144,379,496,711))
Click "PaymentDate"
TypeText PayDate
ScrollWheelDown 1

Click (Image:"AddMoney", WaitFor:1)
Click "SubmitRemittance"

to takeScreenshot  name
	RefreshScreen
	wait 5
	CaptureScreen (Name: name)
	logsuccess "Screenshot " & name &".png Taken"
end takeScreenshot
