(*
This is a script to transfer a single transaction from an encouter to another encounter on Revenue Cycle Application
Ma046396
01/30/2017
*)

(*Prerequisities:
1. Ensure Starting Point is at Patient Account Perspective 
2. Ensure Transfer Transaction Window is in Java version
3. Ensure a transaction is available for transfer
4. Note position of transaction to be transfer
*)

Put "2" into TransactionPostion
Put "1442" into DestinationEnctrNum
Put "Enitan, Adebayo" into DestinationPatientName

//Locate Transaction and open Transfer Transaction Window
Click (Image:"SelfPayTransactionsTab", WaitFor:4)
Click "FirstTransaction"
Repeat TransactionPostion-1 times
	typetext downArrow
End Repeat
RightClick "SelectedTransaction"
Click (Image:"SelectTransferOption", WaitFor:8)
Click "SelectDestination"
TypeText EnctrNum, returnkey
Wait 1
Click(Text:DestinationPatientName)
//Save
Click (Image:"OKButton", WaitFor:6)
// OK
Click "OKButton"

