If ImageFound(2, "ErrorMessage") then
	Click Text:"OK", searchRectangle:((428,235,850,431))
else 
	Click "OKButton"
End if

Answer "What is your name?" from list ("Mary", "Ken", "Tim") //allow multiple //with "Mary"

Log it

Ask "Where are you?" with "I am at the store" 
//title "Question of the Day" message "Learn from this"

Log it

Set the searchRectangle to (322,276,529,432)
If ImageFound(text:"2015")
	Log "Image found"
else
	log "No Image Found"
	
End If
